"""add JSON column for adapter config

Revision ID: 1ad78c075e23
Revises: eecf5ddd71b9
Create Date: 2026-01-11 12:36:24.097023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ad78c075e23'
down_revision: Union[str, Sequence[str], None] = 'eecf5ddd71b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'tags',
               existing_type=postgresql.ARRAY(postgresql.ENUM('hallucination', 'incorrect', 'speculative', 'incomplete', 'overcomplete', 'partial_compliance', 'wrong_format', 'ignored_constraints', 'unclear', 'verbose', 'too_short', 'unsafe', 'policy_violation', name='feedback_tag_enum')),
               nullable=True)
    op.add_column('model_version', sa.Column('adapter_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_version', 'adapter_config')
    op.alter_column('feedback', 'tags',
               existing_type=postgresql.ARRAY(postgresql.ENUM('hallucination', 'incorrect', 'speculative', 'incomplete', 'overcomplete', 'partial_compliance', 'wrong_format', 'ignored_constraints', 'unclear', 'verbose', 'too_short', 'unsafe', 'policy_violation', name='feedback_tag_enum')),
               nullable=False)
    # ### end Alembic commands ###
