"""made org emails unique

Revision ID: 231d4204ee8c
Revises: 705994b6f664
Create Date: 2025-12-20 09:56:40.381716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231d4204ee8c'
down_revision: Union[str, Sequence[str], None] = '705994b6f664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organization', ['contact_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='unique')
    # ### end Alembic commands ###
