"""added otp table

Revision ID: 291387f6945d
Revises: 1ad78c075e23
Create Date: 2026-01-18 19:08:01.231585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291387f6945d'
down_revision: Union[str, Sequence[str], None] = '1ad78c075e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('LENGTH(otp_code) = 6', name='otp_code_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_email'), 'otp', ['email'], unique=True)
    op.create_index(op.f('ix_otp_id'), 'otp', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_id'), table_name='otp')
    op.drop_index(op.f('ix_otp_email'), table_name='otp')
    op.drop_table('otp')
    # ### end Alembic commands ###
