"""added model name to the Org

Revision ID: 30d09c87c801
Revises: e554bb947562
Create Date: 2025-12-23 23:34:05.232861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d09c87c801'
down_revision: Union[str, Sequence[str], None] = 'e554bb947562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('model', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'model')
    # ### end Alembic commands ###
