"""add llm api key to organization

Revision ID: 42b57e0b4b7d
Revises: 231d4204ee8c
Create Date: 2025-12-21 13:09:32.706280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b57e0b4b7d'
down_revision: Union[str, Sequence[str], None] = '231d4204ee8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('llm_api_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'llm_api_key_encrypted')
    # ### end Alembic commands ###
