"""model version lineage and feedback anchoring

Revision ID: 5362340bf016
Revises: 3069e0140596
Create Date: 2026-01-07 22:43:04.371334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5362340bf016'
down_revision: Union[str, Sequence[str], None] = '3069e0140596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Remove FK dependency FIRST
    op.drop_constraint(
        op.f('model_version_dataset_version_id_fkey'),
        'model_version',
        type_='foreignkey'
    )

    # 2. Drop the dependent column
    op.drop_column('model_version', 'dataset_version_id')

    # 3. Now it is safe to drop the table
    op.drop_table('dataset_version')

    # 4. Feedback anchoring
    op.add_column(
        'feedback',
        sa.Column('model_version_id', sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        None,
        'feedback',
        'model_version',
        ['model_version_id'],
        ['id']
    )
    op.drop_column('feedback', 'version')

    # 5. Model lineage + snapshot
    op.add_column(
        'model_version',
        sa.Column('parent_model_version_id', sa.UUID(), nullable=True)
    )
    op.add_column(
        'model_version',
        sa.Column('feedback_ids', sa.ARRAY(sa.UUID()), nullable=False)
    )
    op.create_foreign_key(
        None,
        'model_version',
        'model_version',
        ['parent_model_version_id'],
        ['id']
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_version', sa.Column('dataset_version_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model_version', type_='foreignkey')
    op.create_foreign_key(op.f('model_version_dataset_version_id_fkey'), 'model_version', 'dataset_version', ['dataset_version_id'], ['id'])
    op.drop_column('model_version', 'feedback_ids')
    op.drop_column('model_version', 'parent_model_version_id')
    op.add_column('feedback', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'model_version_id')
    op.create_table('dataset_version',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_model_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('jsonl_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('dataset_version_org_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dataset_version_pkey'))
    )
    # ### end Alembic commands ###
